apiVersion: apps/v1
kind: Deployment
metadata:
  name: cohortservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cohortservice
  template:
    metadata:
      labels:
        app: cohortservice
    spec:
      containers:
      - name: cohortservice
        # Using the image built by Docker Compose
        image: financeservices-cohortservice:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/mydb
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: postgres
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka-server:8761/eureka/
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
        - name: SPRING_PROFILES_ACTIVE
          value: prod
---
apiVersion: v1
kind: Service
metadata:
  name: cohortservice
spec:
  selector:
    app: cohortservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
