apiVersion: v1
kind: ConfigMap
metadata:
  name: config-repo-cm
data:
  cohortservice.properties: |
    spring.application.name=cohortservice
    server.port=8080
    spring.datasource.url=jdbc:postgresql://postgres:5432/mydb
    spring.datasource.username=postgres
    spring.datasource.password=postgres
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    spring.kafka.bootstrap-servers=kafka:9092

  processingservice.properties: |
    spring.application.name=processingservice
    server.port=8082
    services.cohortservice.base-url=http://cohortservice:8080/api
    eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    spring.kafka.consumer.bootstrap-servers=kafka:9092
    resilience4j.circuitbreaker.instances.cohortService.slidingWindowSize=10
    resilience4j.circuitbreaker.instances.cohortService.failureRateThreshold=50
    resilience4j.circuitbreaker.instances.cohortService.waitDurationInOpenState=5s
    resilience4j.retry.instances.cohortService.maxAttempts=3
    resilience4j.retry.instances.cohortService.waitDuration=2s
    resilience4j.ratelimiter.instances.cohortService.limitForPeriod=5
    resilience4j.ratelimiter.instances.cohortService.limitRefreshPeriod=10s
