server:
  port: 8082

spring:
  application:
    name: processingservice
  kafka:
    bootstrap-servers: "${KAFKA_BOOTSTRAP_SERVERS:b-1.xxxx.kafka.us-east-1.amazonaws.com:9092}"
    consumer:
      group-id: processing-group-prod
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
