apiVersion: v1
kind: ConfigMap
metadata:
  name: finance-config
data:
  SPRING_PROFILES_ACTIVE: "dev"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/mydb"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SPRING_CLOUD_AWS_SECRETSMANAGER_ENABLED: "false"
  SPRING_CLOUD_AWS_S3_ENABLED: "false"
  # Override specific imports that might be in application properties
  SPRING_CONFIG_IMPORT: ""
  logging.level.root: "INFO"
  management.endpoints.web.exposure.include: "*"
  management.endpoint.health.show-details: "always"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
  # Support Actuator liveness/readiness
  management.endpoint.health.probes.enabled: "true"
