apiVersion: v1
kind: ConfigMap
metadata:
  name: finance-config
data:
  SPRING_PROFILES_ACTIVE: "prod"
  EUREKA_CLIENT_ENABLED: "false"
  SPRING_CLOUD_CONFIG_ENABLED: "false"
  SPRING_CLOUD_AWS_SECRETSMANAGER_ENABLED: "false"
  SPRING_CLOUD_AWS_S3_ENABLED: "false"
  logging.level.root: "INFO"
  management.endpoints.web.exposure.include: "*"
  management.endpoint.health.show-details: "always"
