apiVersion: v1
kind: ConfigMap
metadata:
  name: finance-config
data:
  SPRING_PROFILES_ACTIVE: "prod"
  # Shared Configs (previously in Config Server)
  logging.level.root: "INFO"
  management.endpoints.web.exposure.include: "*"
