apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-ui
  template:
    metadata:
      labels:
        app: finance-ui
    spec:
      containers:
      - name: finance-ui
        image: finance-ui:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: finance-ui
spec:
  selector:
    app: finance-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
