apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finance-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      # Cohort Service
      - path: /finance/(api/policies.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: cohortservice
            port:
              number: 8080
      - path: /finance/(api/cashflows.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: cohortservice
            port:
              number: 8080
      # Processing Service
      - path: /finance/(api/processing.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: processingservice
            port:
              number: 8082
      # UI
      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: finance-ui
            port:
              number: 80
