apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres.yml
  - kafka.yml
  - cohortservice.yml
  - processingservice.yml
  - cashflowservice.yml
  - gateway.yml
  - httproutes.yml
  - ingress.yml
  - finance-ui.yml
  - configmap.yml
  - service-configs.yml
  - rbac.yml
