apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres.yml
  - eureka-server.yml
  - cohortservice.yml
  - processingservice.yml
  - kafka.yml
  - configserver.yml
  - config-repo-cm.yml
  - apigateway.yml
  - ingress.yml
  - finance-ui.yml
