apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres.yml
  - kafka.yml
  - cohortservice.yml
  - processingservice.yml
  - ingress.yml
  - finance-ui.yml
  - configmap.yml
