apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-cloud-kubernetes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spring-cloud-kubernetes-role
rules:
- apiGroups: [""]
  resources: ["services", "configmaps", "pods", "endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-cloud-kubernetes-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spring-cloud-kubernetes-role
subjects:
- kind: ServiceAccount
  name: spring-cloud-kubernetes
