apiVersion: v1
kind: Secret
metadata:
  name: finance-secrets
type: Opaque
stringData:
  # Using stringData allows us to provide plain text which K8s will encode
  SPRING_DATASOURCE_PASSWORD: "postgres"
