apiVersion: v1
kind: ConfigMap
metadata:
  name: cohortservice
data:
  application.yaml: |
    spring:
      kafka:
        producer:
          transaction-id-prefix: cohort-tx-k8s-
    logging:
      level:
        com:
          nous:
            cohortservice: DEBUG
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: processingservice
data:
  application.yaml: |
    spring:
      cloud:
        openfeign:
          client:
            config:
              cohortservice:
                connectTimeout: 5000
                readTimeout: 5000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cashflowservice
data:
  application.yaml: |
    server:
      port: 8083
    spring:
      kafka:
        consumer:
          group-id: cashflow-group-k8s
